#!/bin/bash
VERSION=1 # Increment manually for now
PREV_VERSION="$((VERSION-1))"
GITHUB_REGISTRY="ghcr.io/nchan18"
IMAGE_NAME="matlab"
echo "Building image $GITHUB_REGISTRY/$IMAGE_NAME:$VERSION from $GITHUB_REGISTRY/$IMAGE_NAME:$PREV_VERSION"
docker buildx build --platform linux/amd64 -t $GITHUB_REGISTRY/$IMAGE_NAME:$VERSION --load .
echo "Build finished"
echo "Would you like to run the image in interactive mode? (y/n)"
read INTERACTIVE
if [ "$INTERACTIVE" = "y" ]; then
    docker run --rm -it $GITHUB_REGISTRY/$IMAGE_NAME:$VERSION zsh
fi
echo "Would you like to push the image to the registry? (y/n)"
read PUSH
if [ "$PUSH" = "y" ]; then
    docker push $GITHUB_REGISTRY/$IMAGE_NAME:$VERSION
fi
rm -rf src